// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr01h1e0tE_lVMdqMGQP6AR8RapE8W19A',
    appId: '1:517084077434:web:02ec725e500b242c014ac3',
    messagingSenderId: '517084077434',
    projectId: 'aitripplanner-9890b',
    authDomain: 'aitripplanner-9890b.firebaseapp.com',
    storageBucket: 'aitripplanner-9890b.appspot.com',
    measurementId: 'G-4H33HEEKCF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANXKbf9jHxLoDFl3B3FSnLRXVnBwvS-Ok',
    appId: '1:517084077434:android:cd18d6f68d779250014ac3',
    messagingSenderId: '517084077434',
    projectId: 'aitripplanner-9890b',
    storageBucket: 'aitripplanner-9890b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkhM_KYLoVq-cRvdbK0R39H4Bp8RapxsU',
    appId: '1:517084077434:ios:89344663625341f1014ac3',
    messagingSenderId: '517084077434',
    projectId: 'aitripplanner-9890b',
    storageBucket: 'aitripplanner-9890b.appspot.com',
    iosClientId: '517084077434-8erl3sg4epu972ncu4qgup7fme8jlbpl.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiTripPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkhM_KYLoVq-cRvdbK0R39H4Bp8RapxsU',
    appId: '1:517084077434:ios:89344663625341f1014ac3',
    messagingSenderId: '517084077434',
    projectId: 'aitripplanner-9890b',
    storageBucket: 'aitripplanner-9890b.appspot.com',
    iosClientId: '517084077434-8erl3sg4epu972ncu4qgup7fme8jlbpl.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiTripPlanner',
  );
}
